(source melpa)

(depends-on "ag")
(depends-on "auto-complete")
(depends-on "coffee-mode")
(depends-on "enh-ruby-mode")
(depends-on "flx-ido")
(depends-on "highlight-indentation")
(depends-on "ido")
(depends-on "magit")
(depends-on "neotree")
(depends-on "pallet")
(depends-on "projectile")
(depends-on "racket-mode")
(depends-on "robe")
(depends-on "smartparens")
(depends-on "web-mode")
