(source melpa)

(depends-on "ag")
(depends-on "auto-complete")
(depends-on "flx-ido")
(depends-on "ido")
(depends-on "magit")
(depends-on "neotree")
(depends-on "pallet")
(depends-on "projectile")
(depends-on "web-mode")
